/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Documents: () => import('#controllers/documents_controller'),
  Home: () => import('#controllers/home_controller'),
  OidcSession: () => import('#controllers/oidc_session_controller'),
}
