/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppUserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'updatedAt'] as const
  $columns = AppUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuthMfaSchema extends BaseModel {
  static $columns = ['accountId', 'lastTotpStep', 'mfaEnabledAt', 'recoveryCodes', 'totpSecret'] as const
  $columns = AuthMfaSchema.$columns
  @column({ isPrimary: true })
  declare accountId: string
  @column()
  declare lastTotpStep: bigint | number | null
  @column.dateTime()
  declare mfaEnabledAt: DateTime | null
  @column()
  declare recoveryCodes: any | null
  @column()
  declare totpSecret: string | null
}

export class AuthOrganizationInvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'expiresAt', 'id', 'invitedBy', 'organizationId', 'role', 'tokenHash', 'updatedAt'] as const
  $columns = AuthOrganizationInvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invitedBy: string
  @column()
  declare organizationId: string
  @column()
  declare role: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthOrganizationMemberSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'id', 'organizationId', 'role', 'updatedAt'] as const
  $columns = AuthOrganizationMemberSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthOrganizationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'logoUrl', 'metadata', 'name', 'slug', 'updatedAt'] as const
  $columns = AuthOrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logoUrl: string | null
  @column()
  declare metadata: any | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthPasswordHistorySchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'id', 'passwordHash'] as const
  $columns = AuthPasswordHistorySchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare passwordHash: string
}

export class AuthSessionRevocationSchema extends BaseModel {
  static $columns = ['id', 'revokedAt', 'sid', 'sub'] as const
  $columns = AuthSessionRevocationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare revokedAt: DateTime
  @column()
  declare sid: string | null
  @column()
  declare sub: string | null
}

export class AuthSettingSchema extends BaseModel {
  static $columns = ['key', 'organizationId', 'updatedAt', 'updatedBy', 'value'] as const
  $columns = AuthSettingSchema.$columns
  @column()
  declare key: string
  @column()
  declare organizationId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: string | null
  @column()
  declare value: string
}

export class AuthUserSchema extends BaseModel {
  static $columns = ['email', 'emailVerificationToken', 'emailVerifiedAt', 'fullName', 'globalRoles', 'id', 'password', 'passwordResetExpiresAt', 'passwordResetToken'] as const
  $columns = AuthUserSchema.$columns
  @column()
  declare email: string
  @column()
  declare emailVerificationToken: string | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column()
  declare globalRoles: string
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordResetExpiresAt: DateTime | null
  @column()
  declare passwordResetToken: string | null
}

export class AuthkitOidcPayloadSchema extends BaseModel {
  static $columns = ['expiresAt', 'grantId', 'id', 'modelName', 'payload', 'uid', 'userCode'] as const
  $columns = AuthkitOidcPayloadSchema.$columns
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare grantId: string | null
  @column()
  declare id: string
  @column({ isPrimary: true })
  declare modelName: string
  @column()
  declare payload: string
  @column()
  declare uid: string | null
  @column()
  declare userCode: string | null
}

export class AuthzPermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'guard', 'id', 'name'] as const
  $columns = AuthzPermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare guard: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
}

export class AuthzRolePermissionSchema extends BaseModel {
  static $columns = ['permissionId', 'roleId'] as const
  $columns = AuthzRolePermissionSchema.$columns
  @column()
  declare permissionId: string
  @column({ isPrimary: true })
  declare roleId: string
}

export class AuthzRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'guard', 'id', 'name'] as const
  $columns = AuthzRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare guard: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
}

export class AuthzUserPermissionSchema extends BaseModel {
  static $columns = ['permissionId', 'userId', 'userType'] as const
  $columns = AuthzUserPermissionSchema.$columns
  @column()
  declare permissionId: string
  @column()
  declare userId: string
  @column({ isPrimary: true })
  declare userType: string
}

export class AuthzUserRoleSchema extends BaseModel {
  static $columns = ['roleId', 'tenantId', 'userId', 'userType'] as const
  $columns = AuthzUserRoleSchema.$columns
  @column()
  declare roleId: string
  @column()
  declare tenantId: string
  @column()
  declare userId: string
  @column({ isPrimary: true })
  declare userType: string
}

export class DocumentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ownerUserId', 'title', 'updatedAt'] as const
  $columns = DocumentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ownerUserId: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MediaSchema extends BaseModel {
  static $columns = ['collection', 'conversions', 'createdAt', 'customProperties', 'disk', 'fileName', 'id', 'mimeType', 'name', 'order', 'ownerId', 'ownerType', 'path', 'size', 'updatedAt'] as const
  $columns = MediaSchema.$columns
  @column()
  declare collection: string
  @column()
  declare conversions: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customProperties: string | null
  @column()
  declare disk: string
  @column()
  declare fileName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string
  @column()
  declare name: string
  @column()
  declare order: number
  @column()
  declare ownerId: string
  @column()
  declare ownerType: string
  @column()
  declare path: string
  @column()
  declare size: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MediaUploadPartSchema extends BaseModel {
  static $columns = ['etag', 'partNumber', 'sessionId'] as const
  $columns = MediaUploadPartSchema.$columns
  @column()
  declare etag: string
  @column()
  declare partNumber: number
  @column({ isPrimary: true })
  declare sessionId: string
}

export class MediaUploadSessionSchema extends BaseModel {
  static $columns = ['contentType', 'createdAt', 'disk', 'expiresAt', 'id', 'key', 'metadata', 'multipartUploadId', 'offset', 'parts', 'size'] as const
  $columns = MediaUploadSessionSchema.$columns
  @column()
  declare contentType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare disk: string
  @column()
  declare expiresAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare metadata: string | null
  @column()
  declare multipartUploadId: string | null
  @column()
  declare offset: bigint | number
  @column()
  declare parts: number
  @column()
  declare size: bigint | number | null
}

export class TelescopeEntrySchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'durationMs', 'familyHash', 'id', 'origin', 'sequence', 'tags', 'traceId', 'type'] as const
  $columns = TelescopeEntrySchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column()
  declare familyHash: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare origin: string
  @column()
  declare sequence: number
  @column()
  declare tags: string
  @column()
  declare traceId: string | null
  @column()
  declare type: string
}
